### ISSUE TITLE
Deprecated selector in `polymorph/styles/polymorph.less`

### ISSUE THREAD

**Issue by ck-jrd** [halohalospecial/atom-polymorph#2]
In `polymorph/styles/polymorph.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .polymorph-source .region,
atom-text-editor::shadow .polymorph-source .region` => `atom-text-editor .polymorph-source .region,
atom-text-editor.editor .polymorph-source .region`

* `atom-text-editor .polymorph-shadow .region,
atom-text-editor::shadow .polymorph-shadow .region` => `atom-text-editor .polymorph-shadow .region,
atom-text-editor.editor .polymorph-shadow .region`

* `atom-text-editor .polymorph-shadow-flash .region,
atom-text-editor::shadow .polymorph-shadow-flash .region` => `atom-text-editor .polymorph-shadow-flash .region,
atom-text-editor.editor .polymorph-shadow-flash .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by halohalospecial** [comment]
@v0wels thank you for reporting!  You can check out the latest version (2.1.4).  Thanks!
